In [29]:
import numpy as np

In [3]:
array = np.array(range (5))
#panda making an array for first 5 numbers

In [4]:
array
#it will just output the array

array([0, 1, 2, 3, 4])

In [5]:
array_loop = [x * 10 for x in range(1,12)]
array_loop = np.array(array_loop)

array_loop

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

- range includes first param, excludes the last one
- we are re assigning the array by going through np so that we can perform numpy

In [6]:
array_loop = [x * 10 for x in range(1,11)]
array_loop = np.array(array_loop).reshape(5,2)
array_loop

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

- reshape will shape the existing array to (**row number**, **column number** )
- the parameters should match accordingly ( Like we cant put 5, 3 here )  , cuz 5X3=15, but here we got 10 entries

In [7]:
array_2d = np.array([range (5),range (5)])
#panda making a 2D array for first 5 by 5 numbers

array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [8]:
array.shape

(5,)

In [9]:
array_2d.shape

(2, 5)

**shape** will say ***(row number , column number )*** 

for 1D array , *it will only return the column number at first* , which is confusing

In [10]:
array_2d.T


array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

 array_2d.T will make a new ***transpose matrix***

 The transpose of a matrix is a new matrix obtained by **interchanging** its rows and columns

In [11]:
array.size
#will return array length

5

In [12]:
array_2d.size

10

In [13]:
array.ndim
#will retuen number of dimension

1

In [14]:
array_2d.ndim

2

In [15]:
array.dtype
#return data type

dtype('int64')

In [16]:
array_2d.dtype

dtype('int64')

In [17]:
np.array(['This','is','RIFFF'])

array(['This', 'is', 'RIFFF'], dtype='<U5')

- **<** : Indicates little-endian byte order (which is generally the default for most systems).
- **U5**: Refers to Unicode string with a maximum length of 5 characters. The U stands for Unicode, and 5 specifies the maximum length of the string.

# Making 2D Array in pandas

In [18]:
#making an array with 5 rows and 2 colummn
array_01 = np.array(list(range(1, 11))).reshape(5, 2)

array_01

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
#another way 
rows = []

# Loop to generate rows
for i in range(5):
    row = [2 * i + 1, 2 * i + 2]  # This creates pairs (1, 2), (3, 4), etc.
    rows.append(row)

# Convert the list of rows into a NumPy array
array_01 = np.array(rows)

array_01

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Making array of random Numbers

In [20]:
np.random.seed(100)

# Create a 4x4 array of random numbers between 0 and 1
array_random = np.random.rand(4, 4)

array_random

array([[0.54340494, 0.27836939, 0.42451759, 0.84477613],
       [0.00471886, 0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195, 0.20920212],
       [0.18532822, 0.10837689, 0.21969749, 0.97862378]])

### seed
- The random seed is a number (in this case, 100) used by the random number generator algorithm to ensure that the sequence of random numbers produced is always the same each time you run the code.
- Without setting a seed, the sequence of random numbers would be different each time you run the code.
- **Reproducibility**: By setting the seed, you ensure that you can reproduce the exact same set of random numbers in the future, which is useful for debugging and testing.
- 
### np.random.rand() 
this generates random numbers from a uniform distribution over the interval [0, 1). This means the numbers will be between 0 (inclusive) and 1 (exclusive).

- np.random.rand(m, n) will generate  m by n array with random numbers from 0 to 1
- if we wanna generate random numbers from 0 to x , just multiply it
- 
Like *np.random.rand(m, n) * x*

In [21]:
# Create a 4x4 array of random numbers between 0 and 5
array_random = np.random.rand(4, 4) * 5

array_random

array([[4.05841575, 0.85970506, 4.08112374, 1.37036874],
       [2.15852092, 4.7001491 , 4.08824689, 1.68055975],
       [0.87705227, 1.86416023, 0.02844254, 1.26213177],
       [3.97831254, 0.07627486, 2.99421688, 3.0190227 ]])

- **np.ones((rows,cols),dtypes)** Creates an array of ones of a given size, as float by default
- **np.zeros((rows, cols), dtype)** Creates an array of zeros of a given size, as float by default
- **np.arange(start, stop, step)** Creates an array of integers with given start & stop values, and a step size (only stop is required, and is not inclusive)
- **np.linspace(start, stop, n)** Creates an array of floats with given start & stop values with n elements, separated by a consistent step size (stop is inclusive)
- **np.array.reshape(rows, cols)**  Changes an array into the specified dimensions, if compatible

In [31]:
np.ones((5,),)

array([1., 1., 1., 1., 1.])

In [23]:
np.ones((5,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1, 10, 5)

array([1, 6])

In [26]:
np.linspace(0, 100, 5) 

array([  0.,  25.,  50.,  75., 100.])

## Problem Statement
**Make an array 5X2 with all 10th numbers**

### Solution

In [34]:
array_10namta = np.linspace(10, 100, 10).reshape(5,2)
array_10namta

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [35]:
array_10namta = np.arange(10, 101, 10).reshape(5,2)
array_10namta

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [38]:
array_10namta = (np.arange(1, 11)* 10)
array_10namta

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [39]:
array_10namta = (np.arange(1, 11)* 10).reshape(5,2)
array_10namta

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])